module.exports = 
[
    {
        "AccountId": "001e000000QmfIuAAJ",
        "ContactId": null,
        "LeadId": null,
        "Id": "003e000000QSsVgAAL",
        "CaseNumber": "00275970",
        "CreatedBy": "Leonid Zaverchnev",
        "CreateDate": "2015-01-13T12:24:19-05:00",
        "ClosedDate": null,
        "LastModifiedBy": "Leonid Zaverchnev",
        "LastModifiedDate": "2015-01-13T12:24:19-05:00",
        "IsClosed": false,
        "IsEscalatedToLevel2": false,
        "IsEscalatedToLevel3": false,
        "FollowUpName": null,
        "FollowUpEmail": null,
        "FollowUpPhone": null,
        "Source": null,
        "Owner": {
            "Id": "005e0000001yRukAAE",
            "Name": "Leonid Zaverchnev",
            "Alias": "lzav",
            "Username": "lzaverchnev@morneaushepell.com.morneau"
        },
        "Comments": [],
        "Attachments": [],
        "Subject": null,
        "Description": "CreateDate Test Case Description",
        "CaseType": null,
        "Priority": "Medium",
        "Status": "Open",
        "Origin": "Phone",
        "Reason": "Benefits",
        "Category": "Claim Inquiry",
        "InternalComment": null
    },
    {
        "AccountId": "001e000000QmfIuAAJ",
        "ContactId": null,
        "LeadId": null,
        "Id": "500e0000005na1XAAQ",
        "CaseNumber": "00275969",
        "CreatedBy": "Leonid Zaverchnev",
        "CreateDate": "2015-01-13T12:22:30-05:00",
        "ClosedDate": null,
        "LastModifiedBy": "Leonid Zaverchnev",
        "LastModifiedDate": "2015-01-13T12:22:30-05:00",
        "IsClosed": false,
        "IsEscalatedToLevel2": false,
        "IsEscalatedToLevel3": false,
        "FollowUpName": null,
        "FollowUpEmail": null,
        "FollowUpPhone": null,
        "Source": null,
        "Owner": {
            "Id": "005e0000001yRukAAE",
            "Name": "Leonid Zaverchnev",
            "Alias": "lzav",
            "Username": "lzaverchnev@morneaushepell.com.morneau"
        },
        "Comments": [
            {
                "Id": "00ae0000001EqJ4AAK",
                "CreatedBy": "Leonid Zaverchnev",
                "CreateDate": "2015-01-13T17:22:31.000+0000",
                "CommentBody": "Internal comment test",
                "IsPublished": false
            }
        ],
        "Attachments": [],
        "Subject": null,
        "Description": "CreateDate Test Case Description",
        "CaseType": null,
        "Priority": "Medium",
        "Status": "Open",
        "Origin": "Phone",
        "Reason": "Benefits",
        "Category": "Claim Inquiry",
        "InternalComment": null
    },
    {
        "AccountId": "001e000000QmfIuAAJ",
        "ContactId": null,
        "LeadId": null,
        "Id": "003e000000QSsVgAAL",
        "CaseNumber": "00275968",
        "CreatedBy": "Leonid Zaverchnev",
        "CreateDate": "2015-01-13T12:22:10-05:00",
        "ClosedDate": null,
        "LastModifiedBy": "Leonid Zaverchnev",
        "LastModifiedDate": "2015-01-13T12:22:10-05:00",
        "IsClosed": false,
        "IsEscalatedToLevel2": false,
        "IsEscalatedToLevel3": false,
        "FollowUpName": null,
        "FollowUpEmail": null,
        "FollowUpPhone": null,
        "Source": null,
        "Owner": {
            "Id": "005e0000001yRukAAE",
            "Name": "Leonid Zaverchnev",
            "Alias": "lzav",
            "Username": "lzaverchnev@morneaushepell.com.morneau"
        },
        "Comments": [
            {
                "Id": "00ae0000001EqIzAAK",
                "CreatedBy": "Leonid Zaverchnev",
                "CreateDate": "2015-01-13T17:22:11.000+0000",
                "CommentBody": "Internal comment test",
                "IsPublished": false
            }
        ],
        "Attachments": [],
        "Subject": "CreateDate Test Case",
        "Description": "CreateDate Test Case Description",
        "CaseType": null,
        "Priority": "Medium",
        "Status": "Open",
        "Origin": "Phone",
        "Reason": "Benefits",
        "Category": "Claim Inquiry",
        "InternalComment": null
    },
    {
        "AccountId": "001e000000QmfIuAAJ",
        "ContactId": null,
        "LeadId": null,
        "Id": "500e0000005na1IAAQ",
        "CaseNumber": "00275967",
        "CreatedBy": "Leonid Zaverchnev",
        "CreateDate": "2015-01-13T12:19:28-05:00",
        "ClosedDate": null,
        "LastModifiedBy": "Leonid Zaverchnev",
        "LastModifiedDate": "2015-01-13T12:19:28-05:00",
        "IsClosed": false,
        "IsEscalatedToLevel2": false,
        "IsEscalatedToLevel3": false,
        "FollowUpName": null,
        "FollowUpEmail": null,
        "FollowUpPhone": null,
        "Source": null,
        "Owner": {
            "Id": "005e0000001yRukAAE",
            "Name": "Leonid Zaverchnev",
            "Alias": "lzav",
            "Username": "lzaverchnev@morneaushepell.com.morneau"
        },
        "Comments": [
            {
                "Id": "00ae0000001EqIpAAK",
                "CreatedBy": "Leonid Zaverchnev",
                "CreateDate": "2015-01-13T17:19:30.000+0000",
                "CommentBody": "Internal comment test",
                "IsPublished": false
            }
        ],
        "Attachments": [],
        "Subject": null,
        "Description": "CreateDate Test Case Description",
        "CaseType": "Question",
        "Priority": "Medium",
        "Status": "Open",
        "Origin": "Phone",
        "Reason": "Benefits",
        "Category": "Claim Inquiry",
        "InternalComment": null
    }
]