module.exports = [
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14594800,
        "ucid": null,
        "logTypeCode": "BOL",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "ACSS",
        "logStatusCode": "DONE",
        "logDeliveryCode": "N/A",
        "logIvrModeCode": "NOIVR",
        "question1": "Member Selection",
        "question2": null,
        "answer1": null,
        "answer2": null,
        "escalationTier": 0,
        "isFirstContact": true,
        "questionDate": "2015-05-06T11:31:57.31",
        "answerDate": null,
        "questionUserId": 19805,
        "questionUserCode": "PFADMPP",
        "questionUserName": "PowerFlex Admin",
        "answerUserId": null,
        "answerUserCode": null,
        "answerUserName": null,
        "assignedUserId": 19805,
        "assignedUserCode": "PFADMPP",
        "assignedUserName": "PowerFlex Admin",
        "attachments": [1,2,3],
        "followUps": [1,2,3]
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14594799,
        "ucid": null,
        "logTypeCode": "BOL",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "ACSS",
        "logStatusCode": "DONE",
        "logDeliveryCode": "N/A",
        "logIvrModeCode": "NOIVR",
        "question1": "Member Selection",
        "question2": null,
        "answer1": null,
        "answer2": null,
        "escalationTier": 0,
        "isFirstContact": true,
        "questionDate": "2015-05-06T11:31:06.163",
        "answerDate": null,
        "questionUserId": 19805,
        "questionUserCode": "PFADMPP",
        "questionUserName": "PowerFlex Admin",
        "answerUserId": null,
        "answerUserCode": null,
        "answerUserName": null,
        "assignedUserId": 19805,
        "assignedUserCode": "PFADMPP",
        "assignedUserName": "PowerFlex Admin",
        "attachments": [1,2,3],
        "followUps": []
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14594795,
        "ucid": null,
        "logTypeCode": "BOL",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "ACSS",
        "logStatusCode": "DONE",
        "logDeliveryCode": "N/A",
        "logIvrModeCode": "NOIVR",
        "question1": "Member Selection",
        "question2": null,
        "answer1": null,
        "answer2": null,
        "escalationTier": 0,
        "isFirstContact": true,
        "questionDate": "2015-05-06T11:26:59.977",
        "answerDate": null,
        "questionUserId": 19805,
        "questionUserCode": "PFADMPP",
        "questionUserName": "PowerFlex Admin",
        "answerUserId": null,
        "answerUserCode": null,
        "answerUserName": null,
        "assignedUserId": 19805,
        "assignedUserCode": "PFADMPP",
        "assignedUserName": "PowerFlex Admin",
        "attachments": [],
        "followUps": [1,2,3]
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14594774,
        "ucid": null,
        "logTypeCode": "CALI",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "MVFY",
        "logStatusCode": "DONE",
        "logDeliveryCode": "N/A",
        "logIvrModeCode": "NOIVR",
        "question1": "Member Verification. Agent decided to abandon call.",
        "question2": " Answered incorrectly: DOB, POSTCODE, PROVHOME.",
        "answer1": null,
        "answer2": null,
        "escalationTier": 0,
        "isFirstContact": true,
        "questionDate": "2015-05-05T18:17:38.51",
        "answerDate": null,
        "questionUserId": 12093,
        "questionUserCode": "CMARQUES",
        "questionUserName": "Marques, Carlos",
        "answerUserId": null,
        "answerUserCode": null,
        "answerUserName": null,
        "assignedUserId": 12093,
        "assignedUserCode": "CMARQUES",
        "assignedUserName": "Marques, Carlos",
        "attachments": [],
        "followUps": []
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14594773,
        "ucid": null,
        "logTypeCode": "CALI",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "MVFY",
        "logStatusCode": "DONE",
        "logDeliveryCode": "N/A",
        "logIvrModeCode": "NOIVR",
        "question1": "Member Verification. Agent decided to abandon call.",
        "question2": " Answered incorrectly: DOB, POSTCODE, PROVHOME.",
        "answer1": null,
        "answer2": null,
        "escalationTier": 0,
        "isFirstContact": true,
        "questionDate": "2015-05-05T18:17:37.937",
        "answerDate": null,
        "questionUserId": 12093,
        "questionUserCode": "CMARQUES",
        "questionUserName": "Marques, Carlos",
        "answerUserId": null,
        "answerUserCode": null,
        "answerUserName": null,
        "assignedUserId": 12093,
        "assignedUserCode": "CMARQUES",
        "assignedUserName": "Marques, Carlos",
        "attachments": [],
        "followUps": []
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14594772,
        "ucid": null,
        "logTypeCode": "BOL",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "ACSS",
        "logStatusCode": "DONE",
        "logDeliveryCode": "N/A",
        "logIvrModeCode": "NOIVR",
        "question1": "Member Selection",
        "question2": null,
        "answer1": null,
        "answer2": null,
        "escalationTier": 0,
        "isFirstContact": true,
        "questionDate": "2015-05-05T18:17:37.863",
        "answerDate": null,
        "questionUserId": 12093,
        "questionUserCode": "CMARQUES",
        "questionUserName": "Marques, Carlos",
        "answerUserId": null,
        "answerUserCode": null,
        "answerUserName": null,
        "assignedUserId": 12093,
        "assignedUserCode": "CMARQUES",
        "assignedUserName": "Marques, Carlos",
        "attachments": [],
        "followUps": []
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14594771,
        "ucid": null,
        "logTypeCode": "BOL",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "ACSS",
        "logStatusCode": "DONE",
        "logDeliveryCode": "N/A",
        "logIvrModeCode": "NOIVR",
        "question1": "Test log",
        "question2": null,
        "answer1": null,
        "answer2": null,
        "escalationTier": 0,
        "isFirstContact": true,
        "questionDate": "2015-05-05T18:17:37.51",
        "answerDate": null,
        "questionUserId": 8,
        "questionUserCode": "ADMIN",
        "questionUserName": "Case Manager Administrator",
        "answerUserId": null,
        "answerUserCode": null,
        "answerUserName": null,
        "assignedUserId": 8,
        "assignedUserCode": "ADMIN",
        "assignedUserName": "Case Manager Administrator",
        "attachments": [],
        "followUps": []
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14594770,
        "ucid": null,
        "logTypeCode": "CALI",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "MVFY",
        "logStatusCode": "DONE",
        "logDeliveryCode": "N/A",
        "logIvrModeCode": "NOIVR",
        "question1": "Member Verification. Agent decided to take call.",
        "question2": "Answered correctly: DOB, ADD1. Answered incorrectly: POSTCODE, PROVHOME. Not asked: SIN.",
        "answer1": null,
        "answer2": null,
        "escalationTier": 0,
        "isFirstContact": true,
        "questionDate": "2015-05-05T18:17:35.063",
        "answerDate": null,
        "questionUserId": 12093,
        "questionUserCode": "CMARQUES",
        "questionUserName": "Marques, Carlos",
        "answerUserId": null,
        "answerUserCode": null,
        "answerUserName": null,
        "assignedUserId": 12093,
        "assignedUserCode": "CMARQUES",
        "assignedUserName": "Marques, Carlos",
        "attachments": [],
        "followUps": []
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14594769,
        "ucid": null,
        "logTypeCode": "CALI",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "MVFY",
        "logStatusCode": "DONE",
        "logDeliveryCode": "N/A",
        "logIvrModeCode": "NOIVR",
        "question1": "Member Verification. Agent decided to abandon call.",
        "question2": " Answered incorrectly: DOB, POSTCODE, PROVHOME.",
        "answer1": null,
        "answer2": null,
        "escalationTier": 0,
        "isFirstContact": true,
        "questionDate": "2015-05-05T18:15:05.017",
        "answerDate": null,
        "questionUserId": 12093,
        "questionUserCode": "CMARQUES",
        "questionUserName": "Marques, Carlos",
        "answerUserId": null,
        "answerUserCode": null,
        "answerUserName": null,
        "assignedUserId": 12093,
        "assignedUserCode": "CMARQUES",
        "assignedUserName": "Marques, Carlos",
        "attachments": [],
        "followUps": []
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14594768,
        "ucid": null,
        "logTypeCode": "CALI",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "MVFY",
        "logStatusCode": "DONE",
        "logDeliveryCode": "N/A",
        "logIvrModeCode": "NOIVR",
        "question1": "Member Verification. Agent decided to abandon call.",
        "question2": " Answered incorrectly: DOB, POSTCODE, PROVHOME.",
        "answer1": null,
        "answer2": null,
        "escalationTier": 0,
        "isFirstContact": true,
        "questionDate": "2015-05-05T18:15:03.747",
        "answerDate": null,
        "questionUserId": 12093,
        "questionUserCode": "CMARQUES",
        "questionUserName": "Marques, Carlos",
        "answerUserId": null,
        "answerUserCode": null,
        "answerUserName": null,
        "assignedUserId": 12093,
        "assignedUserCode": "CMARQUES",
        "assignedUserName": "Marques, Carlos",
        "attachments": [],
        "followUps": []
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14594767,
        "ucid": null,
        "logTypeCode": "BOL",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "ACSS",
        "logStatusCode": "DONE",
        "logDeliveryCode": "N/A",
        "logIvrModeCode": "NOIVR",
        "question1": "Member Selection",
        "question2": null,
        "answer1": null,
        "answer2": null,
        "escalationTier": 0,
        "isFirstContact": true,
        "questionDate": "2015-05-05T18:15:03.673",
        "answerDate": null,
        "questionUserId": 12093,
        "questionUserCode": "CMARQUES",
        "questionUserName": "Marques, Carlos",
        "answerUserId": null,
        "answerUserCode": null,
        "answerUserName": null,
        "assignedUserId": 12093,
        "assignedUserCode": "CMARQUES",
        "assignedUserName": "Marques, Carlos",
        "attachments": [],
        "followUps": []
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14594766,
        "ucid": null,
        "logTypeCode": "BOL",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "ACSS",
        "logStatusCode": "DONE",
        "logDeliveryCode": "N/A",
        "logIvrModeCode": "NOIVR",
        "question1": "Test log",
        "question2": null,
        "answer1": null,
        "answer2": null,
        "escalationTier": 0,
        "isFirstContact": true,
        "questionDate": "2015-05-05T18:15:03.1",
        "answerDate": null,
        "questionUserId": 8,
        "questionUserCode": "ADMIN",
        "questionUserName": "Case Manager Administrator",
        "answerUserId": null,
        "answerUserCode": null,
        "answerUserName": null,
        "assignedUserId": 8,
        "assignedUserCode": "ADMIN",
        "assignedUserName": "Case Manager Administrator",
        "attachments": [],
        "followUps": []
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14594765,
        "ucid": null,
        "logTypeCode": "CALI",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "MVFY",
        "logStatusCode": "DONE",
        "logDeliveryCode": "N/A",
        "logIvrModeCode": "NOIVR",
        "question1": "Member Verification. Agent decided to take call.",
        "question2": "Answered correctly: DOB, ADD1. Answered incorrectly: POSTCODE, PROVHOME. Not asked: SIN.",
        "answer1": null,
        "answer2": null,
        "escalationTier": 0,
        "isFirstContact": true,
        "questionDate": "2015-05-05T18:15:00.49",
        "answerDate": null,
        "questionUserId": 12093,
        "questionUserCode": "CMARQUES",
        "questionUserName": "Marques, Carlos",
        "answerUserId": null,
        "answerUserCode": null,
        "answerUserName": null,
        "assignedUserId": 12093,
        "assignedUserCode": "CMARQUES",
        "assignedUserName": "Marques, Carlos",
        "attachments": [],
        "followUps": []
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14594753,
        "ucid": null,
        "logTypeCode": "DOCI",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "0351",
        "logStatusCode": "DONE",
        "logDeliveryCode": "INPERSON",
        "logIvrModeCode": "NOIVR",
        "question1": "test",
        "question2": null,
        "answer1": "test",
        "answer2": null,
        "escalationTier": 0,
        "isFirstContact": false,
        "questionDate": "2015-05-05T14:58:00",
        "answerDate": "2015-05-05T14:57:00",
        "questionUserId": 8,
        "questionUserCode": "ADMIN",
        "questionUserName": "Case Manager Administrator",
        "answerUserId": 8,
        "answerUserCode": "ADMIN",
        "answerUserName": "Case Manager Administrator",
        "assignedUserId": 8,
        "assignedUserCode": "ADMIN",
        "assignedUserName": "Case Manager Administrator",
        "attachments": [],
        "followUps": []
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14594447,
        "ucid": null,
        "logTypeCode": "DOCI",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "0357",
        "logStatusCode": "DONE",
        "logDeliveryCode": "COURIER",
        "logIvrModeCode": "NOIVR",
        "question1": "This is a test (inbound) document",
        "question2": null,
        "answer1": "This is a test answer for a pending log",
        "answer2": null,
        "escalationTier": 0,
        "isFirstContact": false,
        "questionDate": "2015-04-30T09:19:00",
        "answerDate": "2015-04-30T17:12:00",
        "questionUserId": 8,
        "questionUserCode": "ADMIN",
        "questionUserName": "Case Manager Administrator",
        "answerUserId": 8,
        "answerUserCode": "ADMIN",
        "answerUserName": "Case Manager Administrator",
        "assignedUserId": 8,
        "assignedUserCode": "ADMIN",
        "assignedUserName": "Case Manager Administrator",
        "attachments": [],
        "followUps": []
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14594168,
        "ucid": null,
        "logTypeCode": "BOL",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "ACSS",
        "logStatusCode": "DONE",
        "logDeliveryCode": "N/A",
        "logIvrModeCode": "NOIVR",
        "question1": "Member Selection",
        "question2": null,
        "answer1": null,
        "answer2": null,
        "escalationTier": 0,
        "isFirstContact": true,
        "questionDate": "2015-04-24T12:59:57.39",
        "answerDate": null,
        "questionUserId": 12093,
        "questionUserCode": "CMARQUES",
        "questionUserName": "Marques, Carlos",
        "answerUserId": null,
        "answerUserCode": null,
        "answerUserName": null,
        "assignedUserId": 12093,
        "assignedUserCode": "CMARQUES",
        "assignedUserName": "Marques, Carlos",
        "attachments": [],
        "followUps": []
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14594167,
        "ucid": null,
        "logTypeCode": "BOL",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "ACSS",
        "logStatusCode": "DONE",
        "logDeliveryCode": "N/A",
        "logIvrModeCode": "NOIVR",
        "question1": "Test log",
        "question2": null,
        "answer1": null,
        "answer2": null,
        "escalationTier": 0,
        "isFirstContact": true,
        "questionDate": "2015-04-24T12:59:56.66",
        "answerDate": null,
        "questionUserId": 8,
        "questionUserCode": "ADMIN",
        "questionUserName": "Case Manager Administrator",
        "answerUserId": null,
        "answerUserCode": null,
        "answerUserName": null,
        "assignedUserId": 8,
        "assignedUserCode": "ADMIN",
        "assignedUserName": "Case Manager Administrator",
        "attachments": [],
        "followUps": []
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14594166,
        "ucid": null,
        "logTypeCode": "CALI",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "MVFY",
        "logStatusCode": "DONE",
        "logDeliveryCode": "N/A",
        "logIvrModeCode": "NOIVR",
        "question1": "Member Verification. Agent decided to take call.",
        "question2": "Answered correctly: DOB, ADD1. Answered incorrectly: POSTCODE, PROVHOME. Not asked: SIN.",
        "answer1": null,
        "answer2": null,
        "escalationTier": 0,
        "isFirstContact": true,
        "questionDate": "2015-04-24T12:59:54.647",
        "answerDate": null,
        "questionUserId": 12093,
        "questionUserCode": "CMARQUES",
        "questionUserName": "Marques, Carlos",
        "answerUserId": null,
        "answerUserCode": null,
        "answerUserName": null,
        "assignedUserId": 12093,
        "assignedUserCode": "CMARQUES",
        "assignedUserName": "Marques, Carlos",
        "attachments": [],
        "followUps": []
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14594169,
        "ucid": null,
        "logTypeCode": "CALI",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "0046",
        "logStatusCode": "DONE",
        "logDeliveryCode": "MAIL",
        "logIvrModeCode": "NOIVR",
        "question1": "Member Verification. Agent decided to abandon call. Answered incorrectly: DOB, POSTCODE, PROVHOME.",
        "question2": null,
        "answer1": "test?",
        "answer2": null,
        "escalationTier": 1,
        "isFirstContact": false,
        "questionDate": "2015-04-24T12:59:00",
        "answerDate": "2015-04-30T18:47:00",
        "questionUserId": 12093,
        "questionUserCode": "CMARQUES",
        "questionUserName": "Marques, Carlos",
        "answerUserId": 8,
        "answerUserCode": "ADMIN",
        "answerUserName": "Case Manager Administrator",
        "assignedUserId": 12093,
        "assignedUserCode": "CMARQUES",
        "assignedUserName": "Marques, Carlos",
        "attachments": [],
        "followUps": []
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14594170,
        "ucid": null,
        "logTypeCode": "CALI",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "0054",
        "logStatusCode": "DONE",
        "logDeliveryCode": "MAIL",
        "logIvrModeCode": "NOIVR",
        "question1": "Member Verification. Agent decided to abandon call. Answered incorrectly: DOB, POSTCODE, PROVHOME.",
        "question2": null,
        "answer1": "You can save answers on a closed log? wow...",
        "answer2": null,
        "escalationTier": 1,
        "isFirstContact": false,
        "questionDate": "2015-04-24T12:59:00",
        "answerDate": "2015-04-30T18:46:00",
        "questionUserId": 12093,
        "questionUserCode": "CMARQUES",
        "questionUserName": "Marques, Carlos",
        "answerUserId": 8,
        "answerUserCode": "ADMIN",
        "answerUserName": "Case Manager Administrator",
        "assignedUserId": 12093,
        "assignedUserCode": "CMARQUES",
        "assignedUserName": "Marques, Carlos",
        "attachments": [],
        "followUps": []
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14594107,
        "ucid": null,
        "logTypeCode": "CALI",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "MVFY",
        "logStatusCode": "DONE",
        "logDeliveryCode": "N/A",
        "logIvrModeCode": "NOIVR",
        "question1": "Member Verification. Agent decided to take call.",
        "question2": "Answered correctly: CITY, PROVRES. Answered incorrectly: ADDR2. Not asked: POST.",
        "answer1": null,
        "answer2": null,
        "escalationTier": 0,
        "isFirstContact": true,
        "questionDate": "2015-04-23T15:05:36.47",
        "answerDate": null,
        "questionUserId": 19805,
        "questionUserCode": "PFADMPP",
        "questionUserName": "PowerFlex Admin",
        "answerUserId": null,
        "answerUserCode": null,
        "answerUserName": null,
        "assignedUserId": 19805,
        "assignedUserCode": "PFADMPP",
        "assignedUserName": "PowerFlex Admin",
        "attachments": [],
        "followUps": []
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14594106,
        "ucid": null,
        "logTypeCode": "CALI",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "MVFY",
        "logStatusCode": "DONE",
        "logDeliveryCode": "N/A",
        "logIvrModeCode": "NOIVR",
        "question1": "Member Verification. Agent decided to take call.",
        "question2": "Answered correctly: ADDR2, CITY. Not asked: PROVRES, POST.",
        "answer1": null,
        "answer2": null,
        "escalationTier": 0,
        "isFirstContact": true,
        "questionDate": "2015-04-23T15:04:47.683",
        "answerDate": null,
        "questionUserId": 19805,
        "questionUserCode": "PFADMPP",
        "questionUserName": "PowerFlex Admin",
        "answerUserId": null,
        "answerUserCode": null,
        "answerUserName": null,
        "assignedUserId": 19805,
        "assignedUserCode": "PFADMPP",
        "assignedUserName": "PowerFlex Admin",
        "attachments": [],
        "followUps": []
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14594105,
        "ucid": null,
        "logTypeCode": "CALI",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "MVFY",
        "logStatusCode": "DONE",
        "logDeliveryCode": "N/A",
        "logIvrModeCode": "NOIVR",
        "question1": "Member Verification. Agent decided to take call.",
        "question2": "Answered correctly: ADDR2, CITY. Not asked: PROVRES, POST.",
        "answer1": null,
        "answer2": null,
        "escalationTier": 0,
        "isFirstContact": true,
        "questionDate": "2015-04-23T15:04:35.17",
        "answerDate": null,
        "questionUserId": 19805,
        "questionUserCode": "PFADMPP",
        "questionUserName": "PowerFlex Admin",
        "answerUserId": null,
        "answerUserCode": null,
        "answerUserName": null,
        "assignedUserId": 19805,
        "assignedUserCode": "PFADMPP",
        "assignedUserName": "PowerFlex Admin",
        "attachments": [],
        "followUps": []
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14594062,
        "ucid": null,
        "logTypeCode": "CALI",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "MVFY",
        "logStatusCode": "DONE",
        "logDeliveryCode": "N/A",
        "logIvrModeCode": "NOIVR",
        "question1": "Member Verification. Agent decided to abandon call.",
        "question2": " Answered incorrectly: DOB, POSTCODE, PROVHOME.",
        "answer1": null,
        "answer2": null,
        "escalationTier": 0,
        "isFirstContact": true,
        "questionDate": "2015-04-23T11:54:31.943",
        "answerDate": null,
        "questionUserId": 12093,
        "questionUserCode": "CMARQUES",
        "questionUserName": "Marques, Carlos",
        "answerUserId": null,
        "answerUserCode": null,
        "answerUserName": null,
        "assignedUserId": 12093,
        "assignedUserCode": "CMARQUES",
        "assignedUserName": "Marques, Carlos",
        "attachments": [],
        "followUps": []
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14594061,
        "ucid": null,
        "logTypeCode": "CALI",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "MVFY",
        "logStatusCode": "DONE",
        "logDeliveryCode": "N/A",
        "logIvrModeCode": "NOIVR",
        "question1": "Member Verification. Agent decided to abandon call.",
        "question2": " Answered incorrectly: DOB, POSTCODE, PROVHOME.",
        "answer1": null,
        "answer2": null,
        "escalationTier": 0,
        "isFirstContact": true,
        "questionDate": "2015-04-23T11:54:31.213",
        "answerDate": null,
        "questionUserId": 12093,
        "questionUserCode": "CMARQUES",
        "questionUserName": "Marques, Carlos",
        "answerUserId": null,
        "answerUserCode": null,
        "answerUserName": null,
        "assignedUserId": 12093,
        "assignedUserCode": "CMARQUES",
        "assignedUserName": "Marques, Carlos",
        "attachments": [],
        "followUps": []
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14594060,
        "ucid": null,
        "logTypeCode": "BOL",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "ACSS",
        "logStatusCode": "DONE",
        "logDeliveryCode": "N/A",
        "logIvrModeCode": "NOIVR",
        "question1": "Member Selection",
        "question2": null,
        "answer1": null,
        "answer2": null,
        "escalationTier": 0,
        "isFirstContact": true,
        "questionDate": "2015-04-23T11:54:31.153",
        "answerDate": null,
        "questionUserId": 12093,
        "questionUserCode": "CMARQUES",
        "questionUserName": "Marques, Carlos",
        "answerUserId": null,
        "answerUserCode": null,
        "answerUserName": null,
        "assignedUserId": 12093,
        "assignedUserCode": "CMARQUES",
        "assignedUserName": "Marques, Carlos",
        "attachments": [],
        "followUps": []
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14594059,
        "ucid": null,
        "logTypeCode": "BOL",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "ACSS",
        "logStatusCode": "DONE",
        "logDeliveryCode": "N/A",
        "logIvrModeCode": "NOIVR",
        "question1": "Test log",
        "question2": null,
        "answer1": null,
        "answer2": null,
        "escalationTier": 0,
        "isFirstContact": true,
        "questionDate": "2015-04-23T11:54:31.023",
        "answerDate": null,
        "questionUserId": 8,
        "questionUserCode": "ADMIN",
        "questionUserName": "Case Manager Administrator",
        "answerUserId": null,
        "answerUserCode": null,
        "answerUserName": null,
        "assignedUserId": 8,
        "assignedUserCode": "ADMIN",
        "assignedUserName": "Case Manager Administrator",
        "attachments": [],
        "followUps": []
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14594058,
        "ucid": null,
        "logTypeCode": "CALI",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "MVFY",
        "logStatusCode": "DONE",
        "logDeliveryCode": "N/A",
        "logIvrModeCode": "NOIVR",
        "question1": "Member Verification. Agent decided to take call.",
        "question2": "Answered correctly: DOB, ADD1. Answered incorrectly: POSTCODE, PROVHOME. Not asked: SIN.",
        "answer1": null,
        "answer2": null,
        "escalationTier": 0,
        "isFirstContact": true,
        "questionDate": "2015-04-23T11:54:29.667",
        "answerDate": null,
        "questionUserId": 12093,
        "questionUserCode": "CMARQUES",
        "questionUserName": "Marques, Carlos",
        "answerUserId": null,
        "answerUserCode": null,
        "answerUserName": null,
        "assignedUserId": 12093,
        "assignedUserCode": "CMARQUES",
        "assignedUserName": "Marques, Carlos",
        "attachments": [],
        "followUps": []
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14594034,
        "ucid": null,
        "logTypeCode": "CALI",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "MVFY",
        "logStatusCode": "DONE",
        "logDeliveryCode": "N/A",
        "logIvrModeCode": "NOIVR",
        "question1": "Member Verification. Agent decided to abandon call.",
        "question2": " Answered incorrectly: DOB, POSTCODE, PROVHOME.",
        "answer1": null,
        "answer2": null,
        "escalationTier": 0,
        "isFirstContact": true,
        "questionDate": "2015-04-22T16:20:12.923",
        "answerDate": null,
        "questionUserId": 12093,
        "questionUserCode": "CMARQUES",
        "questionUserName": "Marques, Carlos",
        "answerUserId": null,
        "answerUserCode": null,
        "answerUserName": null,
        "assignedUserId": 12093,
        "assignedUserCode": "CMARQUES",
        "assignedUserName": "Marques, Carlos",
        "attachments": [],
        "followUps": []
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14594033,
        "ucid": null,
        "logTypeCode": "CALI",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "MVFY",
        "logStatusCode": "DONE",
        "logDeliveryCode": "N/A",
        "logIvrModeCode": "NOIVR",
        "question1": "Member Verification. Agent decided to abandon call.",
        "question2": " Answered incorrectly: DOB, POSTCODE, PROVHOME.",
        "answer1": null,
        "answer2": null,
        "escalationTier": 0,
        "isFirstContact": true,
        "questionDate": "2015-04-22T16:20:12.517",
        "answerDate": null,
        "questionUserId": 12093,
        "questionUserCode": "CMARQUES",
        "questionUserName": "Marques, Carlos",
        "answerUserId": null,
        "answerUserCode": null,
        "answerUserName": null,
        "assignedUserId": 12093,
        "assignedUserCode": "CMARQUES",
        "assignedUserName": "Marques, Carlos",
        "attachments": [],
        "followUps": []
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14594032,
        "ucid": null,
        "logTypeCode": "BOL",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "ACSS",
        "logStatusCode": "DONE",
        "logDeliveryCode": "N/A",
        "logIvrModeCode": "NOIVR",
        "question1": "Member Selection",
        "question2": null,
        "answer1": null,
        "answer2": null,
        "escalationTier": 0,
        "isFirstContact": true,
        "questionDate": "2015-04-22T16:20:12.32",
        "answerDate": null,
        "questionUserId": 12093,
        "questionUserCode": "CMARQUES",
        "questionUserName": "Marques, Carlos",
        "answerUserId": null,
        "answerUserCode": null,
        "answerUserName": null,
        "assignedUserId": 12093,
        "assignedUserCode": "CMARQUES",
        "assignedUserName": "Marques, Carlos",
        "attachments": [],
        "followUps": []
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14594031,
        "ucid": null,
        "logTypeCode": "BOL",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "ACSS",
        "logStatusCode": "DONE",
        "logDeliveryCode": "N/A",
        "logIvrModeCode": "NOIVR",
        "question1": "Test log",
        "question2": null,
        "answer1": null,
        "answer2": null,
        "escalationTier": 0,
        "isFirstContact": true,
        "questionDate": "2015-04-22T16:20:12.117",
        "answerDate": null,
        "questionUserId": 8,
        "questionUserCode": "ADMIN",
        "questionUserName": "Case Manager Administrator",
        "answerUserId": null,
        "answerUserCode": null,
        "answerUserName": null,
        "assignedUserId": 8,
        "assignedUserCode": "ADMIN",
        "assignedUserName": "Case Manager Administrator",
        "attachments": [],
        "followUps": []
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14594030,
        "ucid": null,
        "logTypeCode": "CALI",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "MVFY",
        "logStatusCode": "DONE",
        "logDeliveryCode": "N/A",
        "logIvrModeCode": "NOIVR",
        "question1": "Member Verification. Agent decided to take call.",
        "question2": "Answered correctly: DOB, ADD1. Answered incorrectly: POSTCODE, PROVHOME. Not asked: SIN.",
        "answer1": null,
        "answer2": null,
        "escalationTier": 0,
        "isFirstContact": true,
        "questionDate": "2015-04-22T16:20:10.187",
        "answerDate": null,
        "questionUserId": 12093,
        "questionUserCode": "CMARQUES",
        "questionUserName": "Marques, Carlos",
        "answerUserId": null,
        "answerUserCode": null,
        "answerUserName": null,
        "assignedUserId": 12093,
        "assignedUserCode": "CMARQUES",
        "assignedUserName": "Marques, Carlos",
        "attachments": [],
        "followUps": []
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14593942,
        "ucid": null,
        "logTypeCode": "CALI",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "MVFY",
        "logStatusCode": "DONE",
        "logDeliveryCode": "N/A",
        "logIvrModeCode": "NOIVR",
        "question1": "Member Verification. Agent decided to abandon call.",
        "question2": " Answered incorrectly: DOB, POSTCODE, PROVHOME.",
        "answer1": null,
        "answer2": null,
        "escalationTier": 0,
        "isFirstContact": true,
        "questionDate": "2015-04-22T09:27:40.943",
        "answerDate": null,
        "questionUserId": 12093,
        "questionUserCode": "CMARQUES",
        "questionUserName": "Marques, Carlos",
        "answerUserId": null,
        "answerUserCode": null,
        "answerUserName": null,
        "assignedUserId": 12093,
        "assignedUserCode": "CMARQUES",
        "assignedUserName": "Marques, Carlos",
        "attachments": [],
        "followUps": []
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14593941,
        "ucid": null,
        "logTypeCode": "CALI",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "MVFY",
        "logStatusCode": "DONE",
        "logDeliveryCode": "N/A",
        "logIvrModeCode": "NOIVR",
        "question1": "Member Verification. Agent decided to abandon call.",
        "question2": " Answered incorrectly: DOB, POSTCODE, PROVHOME.",
        "answer1": null,
        "answer2": null,
        "escalationTier": 0,
        "isFirstContact": true,
        "questionDate": "2015-04-22T09:27:40.447",
        "answerDate": null,
        "questionUserId": 12093,
        "questionUserCode": "CMARQUES",
        "questionUserName": "Marques, Carlos",
        "answerUserId": null,
        "answerUserCode": null,
        "answerUserName": null,
        "assignedUserId": 12093,
        "assignedUserCode": "CMARQUES",
        "assignedUserName": "Marques, Carlos",
        "attachments": [],
        "followUps": []
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14593940,
        "ucid": null,
        "logTypeCode": "BOL",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "ACSS",
        "logStatusCode": "DONE",
        "logDeliveryCode": "N/A",
        "logIvrModeCode": "NOIVR",
        "question1": "Member Selection",
        "question2": null,
        "answer1": null,
        "answer2": null,
        "escalationTier": 0,
        "isFirstContact": true,
        "questionDate": "2015-04-22T09:27:38.597",
        "answerDate": null,
        "questionUserId": 12093,
        "questionUserCode": "CMARQUES",
        "questionUserName": "Marques, Carlos",
        "answerUserId": null,
        "answerUserCode": null,
        "answerUserName": null,
        "assignedUserId": 12093,
        "assignedUserCode": "CMARQUES",
        "assignedUserName": "Marques, Carlos",
        "attachments": [],
        "followUps": []
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14593939,
        "ucid": null,
        "logTypeCode": "BOL",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "ACSS",
        "logStatusCode": "DONE",
        "logDeliveryCode": "N/A",
        "logIvrModeCode": "NOIVR",
        "question1": "Test log",
        "question2": null,
        "answer1": null,
        "answer2": null,
        "escalationTier": 0,
        "isFirstContact": true,
        "questionDate": "2015-04-22T09:27:38.447",
        "answerDate": null,
        "questionUserId": 8,
        "questionUserCode": "ADMIN",
        "questionUserName": "Case Manager Administrator",
        "answerUserId": null,
        "answerUserCode": null,
        "answerUserName": null,
        "assignedUserId": 8,
        "assignedUserCode": "ADMIN",
        "assignedUserName": "Case Manager Administrator",
        "attachments": [],
        "followUps": []
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14593938,
        "ucid": null,
        "logTypeCode": "CALI",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "MVFY",
        "logStatusCode": "DONE",
        "logDeliveryCode": "N/A",
        "logIvrModeCode": "NOIVR",
        "question1": "Member Verification. Agent decided to take call.",
        "question2": "Answered correctly: DOB, ADD1. Answered incorrectly: POSTCODE, PROVHOME. Not asked: SIN.",
        "answer1": null,
        "answer2": null,
        "escalationTier": 0,
        "isFirstContact": true,
        "questionDate": "2015-04-22T09:27:36.33",
        "answerDate": null,
        "questionUserId": 12093,
        "questionUserCode": "CMARQUES",
        "questionUserName": "Marques, Carlos",
        "answerUserId": null,
        "answerUserCode": null,
        "answerUserName": null,
        "assignedUserId": 12093,
        "assignedUserCode": "CMARQUES",
        "assignedUserName": "Marques, Carlos",
        "attachments": [],
        "followUps": []
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14593937,
        "ucid": null,
        "logTypeCode": "CALI",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "MVFY",
        "logStatusCode": "DONE",
        "logDeliveryCode": "N/A",
        "logIvrModeCode": "NOIVR",
        "question1": "Member Verification. Agent decided to abandon call.",
        "question2": " Answered incorrectly: DOB, POSTCODE, PROVHOME.",
        "answer1": null,
        "answer2": null,
        "escalationTier": 0,
        "isFirstContact": true,
        "questionDate": "2015-04-22T09:26:56.523",
        "answerDate": null,
        "questionUserId": 12093,
        "questionUserCode": "CMARQUES",
        "questionUserName": "Marques, Carlos",
        "answerUserId": null,
        "answerUserCode": null,
        "answerUserName": null,
        "assignedUserId": 12093,
        "assignedUserCode": "CMARQUES",
        "assignedUserName": "Marques, Carlos",
        "attachments": [],
        "followUps": []
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14593936,
        "ucid": null,
        "logTypeCode": "CALI",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "MVFY",
        "logStatusCode": "DONE",
        "logDeliveryCode": "N/A",
        "logIvrModeCode": "NOIVR",
        "question1": "Member Verification. Agent decided to abandon call.",
        "question2": " Answered incorrectly: DOB, POSTCODE, PROVHOME.",
        "answer1": null,
        "answer2": null,
        "escalationTier": 0,
        "isFirstContact": true,
        "questionDate": "2015-04-22T09:26:56.13",
        "answerDate": null,
        "questionUserId": 12093,
        "questionUserCode": "CMARQUES",
        "questionUserName": "Marques, Carlos",
        "answerUserId": null,
        "answerUserCode": null,
        "answerUserName": null,
        "assignedUserId": 12093,
        "assignedUserCode": "CMARQUES",
        "assignedUserName": "Marques, Carlos",
        "attachments": [],
        "followUps": []
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14593935,
        "ucid": null,
        "logTypeCode": "BOL",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "ACSS",
        "logStatusCode": "DONE",
        "logDeliveryCode": "N/A",
        "logIvrModeCode": "NOIVR",
        "question1": "Member Selection",
        "question2": null,
        "answer1": null,
        "answer2": null,
        "escalationTier": 0,
        "isFirstContact": true,
        "questionDate": "2015-04-22T09:26:54.313",
        "answerDate": null,
        "questionUserId": 12093,
        "questionUserCode": "CMARQUES",
        "questionUserName": "Marques, Carlos",
        "answerUserId": null,
        "answerUserCode": null,
        "answerUserName": null,
        "assignedUserId": 12093,
        "assignedUserCode": "CMARQUES",
        "assignedUserName": "Marques, Carlos",
        "attachments": [],
        "followUps": []
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14593934,
        "ucid": null,
        "logTypeCode": "BOL",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "ACSS",
        "logStatusCode": "DONE",
        "logDeliveryCode": "N/A",
        "logIvrModeCode": "NOIVR",
        "question1": "Test log",
        "question2": null,
        "answer1": null,
        "answer2": null,
        "escalationTier": 0,
        "isFirstContact": true,
        "questionDate": "2015-04-22T09:26:54.117",
        "answerDate": null,
        "questionUserId": 8,
        "questionUserCode": "ADMIN",
        "questionUserName": "Case Manager Administrator",
        "answerUserId": null,
        "answerUserCode": null,
        "answerUserName": null,
        "assignedUserId": 8,
        "assignedUserCode": "ADMIN",
        "assignedUserName": "Case Manager Administrator",
        "attachments": [],
        "followUps": []
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14593933,
        "ucid": null,
        "logTypeCode": "CALI",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "MVFY",
        "logStatusCode": "DONE",
        "logDeliveryCode": "N/A",
        "logIvrModeCode": "NOIVR",
        "question1": "Member Verification. Agent decided to take call.",
        "question2": "Answered correctly: DOB, ADD1. Answered incorrectly: POSTCODE, PROVHOME. Not asked: SIN.",
        "answer1": null,
        "answer2": null,
        "escalationTier": 0,
        "isFirstContact": true,
        "questionDate": "2015-04-22T09:26:51.893",
        "answerDate": null,
        "questionUserId": 12093,
        "questionUserCode": "CMARQUES",
        "questionUserName": "Marques, Carlos",
        "answerUserId": null,
        "answerUserCode": null,
        "answerUserName": null,
        "assignedUserId": 12093,
        "assignedUserCode": "CMARQUES",
        "assignedUserName": "Marques, Carlos",
        "attachments": [],
        "followUps": []
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14593927,
        "ucid": null,
        "logTypeCode": "BOL",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "ACSS",
        "logStatusCode": "DONE",
        "logDeliveryCode": "N/A",
        "logIvrModeCode": "NOIVR",
        "question1": "Member Selection",
        "question2": null,
        "answer1": null,
        "answer2": null,
        "escalationTier": 0,
        "isFirstContact": true,
        "questionDate": "2015-04-21T18:34:24.533",
        "answerDate": null,
        "questionUserId": 19805,
        "questionUserCode": "PFADMPP",
        "questionUserName": "PowerFlex Admin",
        "answerUserId": null,
        "answerUserCode": null,
        "answerUserName": null,
        "assignedUserId": 19805,
        "assignedUserCode": "PFADMPP",
        "assignedUserName": "PowerFlex Admin",
        "attachments": [],
        "followUps": []
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14593926,
        "ucid": null,
        "logTypeCode": "BOL",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "ACSS",
        "logStatusCode": "DONE",
        "logDeliveryCode": "N/A",
        "logIvrModeCode": "NOIVR",
        "question1": "Member Selection",
        "question2": null,
        "answer1": null,
        "answer2": null,
        "escalationTier": 0,
        "isFirstContact": true,
        "questionDate": "2015-04-21T18:18:20.55",
        "answerDate": null,
        "questionUserId": 19805,
        "questionUserCode": "PFADMPP",
        "questionUserName": "PowerFlex Admin",
        "answerUserId": null,
        "answerUserCode": null,
        "answerUserName": null,
        "assignedUserId": 19805,
        "assignedUserCode": "PFADMPP",
        "assignedUserName": "PowerFlex Admin",
        "attachments": [],
        "followUps": []
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14593829,
        "ucid": null,
        "logTypeCode": "CALI",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "MVFY",
        "logStatusCode": "DONE",
        "logDeliveryCode": "N/A",
        "logIvrModeCode": "NOIVR",
        "question1": "Member Verification. Agent decided to abandon call.",
        "question2": " Answered incorrectly: DOB, POSTCODE, PROVHOME.",
        "answer1": null,
        "answer2": null,
        "escalationTier": 1,
        "isFirstContact": true,
        "questionDate": "2015-04-20T16:47:39.133",
        "answerDate": null,
        "questionUserId": 12093,
        "questionUserCode": "CMARQUES",
        "questionUserName": "Marques, Carlos",
        "answerUserId": null,
        "answerUserCode": null,
        "answerUserName": null,
        "assignedUserId": 12093,
        "assignedUserCode": "CMARQUES",
        "assignedUserName": "Marques, Carlos",
        "attachments": [],
        "followUps": []
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14593828,
        "ucid": null,
        "logTypeCode": "CALI",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "MVFY",
        "logStatusCode": "DONE",
        "logDeliveryCode": "N/A",
        "logIvrModeCode": "NOIVR",
        "question1": "Member Verification. Agent decided to abandon call.",
        "question2": " Answered incorrectly: DOB, POSTCODE, PROVHOME.",
        "answer1": null,
        "answer2": null,
        "escalationTier": 0,
        "isFirstContact": true,
        "questionDate": "2015-04-20T16:47:39.127",
        "answerDate": null,
        "questionUserId": 12093,
        "questionUserCode": "CMARQUES",
        "questionUserName": "Marques, Carlos",
        "answerUserId": null,
        "answerUserCode": null,
        "answerUserName": null,
        "assignedUserId": 12093,
        "assignedUserCode": "CMARQUES",
        "assignedUserName": "Marques, Carlos",
        "attachments": [],
        "followUps": []
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14593827,
        "ucid": null,
        "logTypeCode": "BOL",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "ACSS",
        "logStatusCode": "DONE",
        "logDeliveryCode": "N/A",
        "logIvrModeCode": "NOIVR",
        "question1": "Member Selection",
        "question2": null,
        "answer1": null,
        "answer2": null,
        "escalationTier": 0,
        "isFirstContact": true,
        "questionDate": "2015-04-20T16:47:39.103",
        "answerDate": null,
        "questionUserId": 12093,
        "questionUserCode": "CMARQUES",
        "questionUserName": "Marques, Carlos",
        "answerUserId": null,
        "answerUserCode": null,
        "answerUserName": null,
        "assignedUserId": 12093,
        "assignedUserCode": "CMARQUES",
        "assignedUserName": "Marques, Carlos",
        "attachments": [],
        "followUps": []
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14593826,
        "ucid": null,
        "logTypeCode": "BOL",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "ACSS",
        "logStatusCode": "DONE",
        "logDeliveryCode": "N/A",
        "logIvrModeCode": "NOIVR",
        "question1": "Test log",
        "question2": null,
        "answer1": null,
        "answer2": null,
        "escalationTier": 0,
        "isFirstContact": true,
        "questionDate": "2015-04-20T16:47:39.043",
        "answerDate": null,
        "questionUserId": 8,
        "questionUserCode": "ADMIN",
        "questionUserName": "Case Manager Administrator",
        "answerUserId": null,
        "answerUserCode": null,
        "answerUserName": null,
        "assignedUserId": 8,
        "assignedUserCode": "ADMIN",
        "assignedUserName": "Case Manager Administrator",
        "attachments": [],
        "followUps": []
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14593825,
        "ucid": null,
        "logTypeCode": "CALI",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "MVFY",
        "logStatusCode": "DONE",
        "logDeliveryCode": "N/A",
        "logIvrModeCode": "NOIVR",
        "question1": "Member Verification. Agent decided to take call.",
        "question2": "Answered correctly: DOB, ADD1. Answered incorrectly: POSTCODE, PROVHOME. Not asked: SIN.",
        "answer1": null,
        "answer2": null,
        "escalationTier": 0,
        "isFirstContact": true,
        "questionDate": "2015-04-20T16:47:36.843",
        "answerDate": null,
        "questionUserId": 12093,
        "questionUserCode": "CMARQUES",
        "questionUserName": "Marques, Carlos",
        "answerUserId": null,
        "answerUserCode": null,
        "answerUserName": null,
        "assignedUserId": 12093,
        "assignedUserCode": "CMARQUES",
        "assignedUserName": "Marques, Carlos",
        "attachments": [],
        "followUps": []
    },
    {
        "clientCode": "CELA",
        "memberId": 12712265,
        "logId": 14593822,
        "ucid": null,
        "logTypeCode": "BOL",
        "logCategoryCode": "GENERAL",
        "logDescriptionCode": "ACSS",
        "logStatusCode": "DONE",
        "logDeliveryCode": "N/A",
        "logIvrModeCode": "NOIVR",
        "question1": "Test log",
        "question2": null,
        "answer1": null,
        "answer2": null,
        "escalationTier": 0,
        "isFirstContact": true,
        "questionDate": "2015-04-20T16:47:12.277",
        "answerDate": null,
        "questionUserId": 8,
        "questionUserCode": "ADMIN",
        "questionUserName": "Case Manager Administrator",
        "answerUserId": null,
        "answerUserCode": null,
        "answerUserName": null,
        "assignedUserId": 8,
        "assignedUserCode": "ADMIN",
        "assignedUserName": "Case Manager Administrator",
        "attachments": [],
        "followUps": []
    }
]