// csrMemberFakeData.js
  /* Search result
   * @param divisionCode 
   * @param memberNo 
   * @param lastName 
   * @param firstName 
   * @param sin 
   * @param emailAddress 
   * @param customAttribute1 
   * @param customAttribute2 
   * @param customAttribute3 
   * @param customAttribute4 
   * @param customAttribute5 
   * @param searchDependents 
   * @param maxRecords 
   */
module.exports = {
    "items": [
        {
            "memberId": "12756135",
            "sin": "135826342",
            "divisionCode": null,
            "memberNumber": "135826342",
            "lastName": "KRISHNAMURTHY",
            "firstName": "SMITHA P",
            "corporateEmailAddress": null,
            "personalEmailAddress": null,
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12765047",
            "sin": "337285584",
            "divisionCode": "MEREDO",
            "memberNumber": "R0019707",
            "lastName": "MENDENHALL",
            "firstName": "SMITH K",
            "corporateEmailAddress": null,
            "personalEmailAddress": null,
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12776542",
            "sin": "642920417",
            "divisionCode": null,
            "memberNumber": "642920417",
            "lastName": "Raphael",
            "firstName": "Smitha",
            "corporateEmailAddress": null,
            "personalEmailAddress": null,
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12784913",
            "sin": "130409772",
            "divisionCode": null,
            "memberNumber": "130409772",
            "lastName": "SMITH",
            "firstName": "A",
            "corporateEmailAddress": null,
            "personalEmailAddress": null,
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12784914",
            "sin": "212567125",
            "divisionCode": null,
            "memberNumber": "212567125",
            "lastName": "SMITH",
            "firstName": "A",
            "corporateEmailAddress": null,
            "personalEmailAddress": null,
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12784900",
            "sin": "253602877",
            "divisionCode": null,
            "memberNumber": "253602877",
            "lastName": "SMITH",
            "firstName": "A",
            "corporateEmailAddress": null,
            "personalEmailAddress": null,
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12784903",
            "sin": "462527599",
            "divisionCode": null,
            "memberNumber": "462527599",
            "lastName": "SMITH",
            "firstName": "A",
            "corporateEmailAddress": null,
            "personalEmailAddress": null,
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12784924",
            "sin": "243457557",
            "divisionCode": "USOTHER",
            "memberNumber": "R0015405",
            "lastName": "Smith",
            "firstName": "Adrian",
            "corporateEmailAddress": null,
            "personalEmailAddress": "cbloom@morneaushepell.com",
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12784899",
            "sin": "128146730",
            "divisionCode": null,
            "memberNumber": "128146730",
            "lastName": "SMITH",
            "firstName": "AILEEN N",
            "corporateEmailAddress": null,
            "personalEmailAddress": null,
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12784925",
            "sin": "407250692",
            "divisionCode": "USOTHER",
            "memberNumber": "9747",
            "lastName": "SMITH",
            "firstName": "ALAN",
            "corporateEmailAddress": null,
            "personalEmailAddress": null,
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12784907",
            "sin": "141666542",
            "divisionCode": "USOTHER",
            "memberNumber": "R0022361",
            "lastName": "SMITH",
            "firstName": "ALAN P",
            "corporateEmailAddress": null,
            "personalEmailAddress": null,
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12784919",
            "sin": "035409090",
            "divisionCode": null,
            "memberNumber": "35409090",
            "lastName": "SMITH",
            "firstName": "ALANA",
            "corporateEmailAddress": null,
            "personalEmailAddress": null,
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12784906",
            "sin": "189304138",
            "divisionCode": null,
            "memberNumber": "189304138",
            "lastName": "SMITH",
            "firstName": "ALBERT E",
            "corporateEmailAddress": null,
            "personalEmailAddress": null,
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12784912",
            "sin": "240842031",
            "divisionCode": "USOTHER",
            "memberNumber": "R0018725",
            "lastName": "SMITH",
            "firstName": "ALBIN B",
            "corporateEmailAddress": null,
            "personalEmailAddress": null,
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12784902",
            "sin": "426462413",
            "divisionCode": null,
            "memberNumber": "426462413",
            "lastName": "SMITH",
            "firstName": "ALFONSO W",
            "corporateEmailAddress": null,
            "personalEmailAddress": null,
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12803254",
            "sin": "465443686",
            "divisionCode": "USOTHER",
            "memberNumber": "R0017054",
            "lastName": "SMITH",
            "firstName": "ALICE ANN",
            "corporateEmailAddress": null,
            "personalEmailAddress": null,
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12784921",
            "sin": "347522246",
            "divisionCode": null,
            "memberNumber": "347522246",
            "lastName": "SMITH",
            "firstName": "ALISON",
            "corporateEmailAddress": null,
            "personalEmailAddress": null,
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12800643",
            "sin": "211333331",
            "divisionCode": "EDMCA",
            "memberNumber": "211333331",
            "lastName": "Smith",
            "firstName": "Allan",
            "corporateEmailAddress": null,
            "personalEmailAddress": null,
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12784893",
            "sin": "214072224",
            "divisionCode": null,
            "memberNumber": "214072224",
            "lastName": "SMITH",
            "firstName": "ALLEN M",
            "corporateEmailAddress": null,
            "personalEmailAddress": null,
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12784892",
            "sin": "217104387",
            "divisionCode": null,
            "memberNumber": "217104387",
            "lastName": "SMITH",
            "firstName": "ALLEN R",
            "corporateEmailAddress": null,
            "personalEmailAddress": null,
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12784896",
            "sin": "217107144",
            "divisionCode": "USOTHER",
            "memberNumber": "R0006952",
            "lastName": "SMITH",
            "firstName": "ALLEN R",
            "corporateEmailAddress": null,
            "personalEmailAddress": null,
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12784909",
            "sin": "220400897",
            "divisionCode": "USOTHER",
            "memberNumber": "R0017276",
            "lastName": "SMITH",
            "firstName": "ALLEN R",
            "corporateEmailAddress": null,
            "personalEmailAddress": null,
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12784905",
            "sin": "247608010",
            "divisionCode": "USOTHER",
            "memberNumber": "R0026038",
            "lastName": "SMITH",
            "firstName": "ALMA",
            "corporateEmailAddress": null,
            "personalEmailAddress": null,
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12784915",
            "sin": "249965657",
            "divisionCode": null,
            "memberNumber": "249965657",
            "lastName": "SMITH",
            "firstName": "ALMON W",
            "corporateEmailAddress": null,
            "personalEmailAddress": null,
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12784910",
            "sin": "406564690",
            "divisionCode": "USOTHER",
            "memberNumber": "R0009587",
            "lastName": "SMITH",
            "firstName": "ALONZO",
            "corporateEmailAddress": null,
            "personalEmailAddress": null,
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12784895",
            "sin": "147070527",
            "divisionCode": null,
            "memberNumber": "147070527",
            "lastName": "SMITH",
            "firstName": "ANDREW",
            "corporateEmailAddress": null,
            "personalEmailAddress": null,
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12784928",
            "sin": "239578648",
            "divisionCode": null,
            "memberNumber": "239578648",
            "lastName": "SMITH",
            "firstName": "ANGELA",
            "corporateEmailAddress": null,
            "personalEmailAddress": null,
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12784929",
            "sin": "463257400",
            "divisionCode": null,
            "memberNumber": "463257400",
            "lastName": "SMITH",
            "firstName": "ANGELA",
            "corporateEmailAddress": null,
            "personalEmailAddress": null,
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12784927",
            "sin": "248061088",
            "divisionCode": "USOTHER",
            "memberNumber": "R0002182",
            "lastName": "SMITH",
            "firstName": "ANGELIA",
            "corporateEmailAddress": null,
            "personalEmailAddress": null,
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12784908",
            "sin": "249523973",
            "divisionCode": "USOTHER",
            "memberNumber": "R0023474",
            "lastName": "SMITH",
            "firstName": "ANN",
            "corporateEmailAddress": null,
            "personalEmailAddress": null,
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12784916",
            "sin": "249928424",
            "divisionCode": null,
            "memberNumber": "249928424",
            "lastName": "SMITH",
            "firstName": "ANNA",
            "corporateEmailAddress": null,
            "personalEmailAddress": null,
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12784897",
            "sin": "367240689",
            "divisionCode": null,
            "memberNumber": "367240689",
            "lastName": "SMITH",
            "firstName": "ANNA",
            "corporateEmailAddress": null,
            "personalEmailAddress": null,
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12784922",
            "sin": "452431996",
            "divisionCode": null,
            "memberNumber": "452431996",
            "lastName": "SMITH",
            "firstName": "ANNETTE M",
            "corporateEmailAddress": null,
            "personalEmailAddress": null,
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12784920",
            "sin": "251157561",
            "divisionCode": null,
            "memberNumber": "251157561",
            "lastName": "SMITH",
            "firstName": "ANNIE",
            "corporateEmailAddress": null,
            "personalEmailAddress": null,
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12784923",
            "sin": "237110336",
            "divisionCode": "USOTHER",
            "memberNumber": "1590",
            "lastName": "SMITH",
            "firstName": "ANTHONY",
            "corporateEmailAddress": null,
            "personalEmailAddress": null,
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12784917",
            "sin": "454026895",
            "divisionCode": "USOTHER",
            "memberNumber": "R0019137",
            "lastName": "SMITH",
            "firstName": "ANTHONY W",
            "corporateEmailAddress": null,
            "personalEmailAddress": "cbloom@morneaushepell.com",
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12784898",
            "sin": "224247971",
            "divisionCode": "CELCO",
            "memberNumber": "R0028361",
            "lastName": "SMITH",
            "firstName": "ARCHIE P",
            "corporateEmailAddress": null,
            "personalEmailAddress": null,
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12784911",
            "sin": "144384202",
            "divisionCode": "USOTHER",
            "memberNumber": "R0004034",
            "lastName": "SMITH",
            "firstName": "ARLEY F",
            "corporateEmailAddress": null,
            "personalEmailAddress": null,
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12784918",
            "sin": "250081761",
            "divisionCode": null,
            "memberNumber": "250081761",
            "lastName": "SMITH",
            "firstName": "ARNOLD",
            "corporateEmailAddress": null,
            "personalEmailAddress": null,
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12784891",
            "sin": "525203495",
            "divisionCode": null,
            "memberNumber": "525203495",
            "lastName": "SMITH",
            "firstName": "ARTHUR B",
            "corporateEmailAddress": null,
            "personalEmailAddress": null,
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12784904",
            "sin": "218302460",
            "divisionCode": "USOTHER",
            "memberNumber": "R0001343",
            "lastName": "SMITH",
            "firstName": "ARTHUR C",
            "corporateEmailAddress": null,
            "personalEmailAddress": null,
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12784894",
            "sin": "214073418",
            "divisionCode": null,
            "memberNumber": "214073418",
            "lastName": "SMITH",
            "firstName": "ARTHUR J",
            "corporateEmailAddress": null,
            "personalEmailAddress": null,
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12784967",
            "sin": "161464191",
            "divisionCode": null,
            "memberNumber": "161464191",
            "lastName": "SMITH",
            "firstName": "B",
            "corporateEmailAddress": null,
            "personalEmailAddress": null,
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12784932",
            "sin": "247185270",
            "divisionCode": null,
            "memberNumber": "247185270",
            "lastName": "SMITH",
            "firstName": "B",
            "corporateEmailAddress": null,
            "personalEmailAddress": null,
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12784951",
            "sin": "248703094",
            "divisionCode": null,
            "memberNumber": "248703094",
            "lastName": "SMITH",
            "firstName": "B",
            "corporateEmailAddress": null,
            "personalEmailAddress": null,
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12784960",
            "sin": "297480298",
            "divisionCode": null,
            "memberNumber": "297480298",
            "lastName": "SMITH",
            "firstName": "B",
            "corporateEmailAddress": null,
            "personalEmailAddress": null,
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12784957",
            "sin": "403661901",
            "divisionCode": null,
            "memberNumber": "403661901",
            "lastName": "SMITH",
            "firstName": "B",
            "corporateEmailAddress": null,
            "personalEmailAddress": null,
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12784946",
            "sin": "464544811",
            "divisionCode": null,
            "memberNumber": "464544811",
            "lastName": "SMITH",
            "firstName": "B",
            "corporateEmailAddress": null,
            "personalEmailAddress": null,
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12784959",
            "sin": "470548750",
            "divisionCode": null,
            "memberNumber": "470548750",
            "lastName": "SMITH",
            "firstName": "B",
            "corporateEmailAddress": null,
            "personalEmailAddress": null,
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        },
        {
            "memberId": "12784942",
            "sin": "524447577",
            "divisionCode": null,
            "memberNumber": "524447577",
            "lastName": "SMITH",
            "firstName": "B",
            "corporateEmailAddress": null,
            "personalEmailAddress": null,
            "customAttribute1": "",
            "customAttribute2": "",
            "customAttribute3": "",
            "customAttribute4": "",
            "customAttribute5": "",
            "homePhoneNumber": null,
            "officePhoneNumber": null,
            "mobilePhoneNumber": null,
            "otherPhoneNumber": null,
            "isDisabled": false,
            "dependents": null
        }
    ],
    "itemsFound": 990
}